# Generated by Django 5.2.17 on 2026-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('bun', models.CharField(max_length=50)),
                ('meat', models.CharField(max_length=50)),
                ('ingredients', models.JSONField(default=list)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
