# Generated by Django 5.2.17 on 2026-09-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_charaters'),
    ]

    operations = [
        migrations.AddField(
            model_name='charaters',
            name='charater_class',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
